service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-product-configuration-management:1.1.0.17.1
helmVersion: 0.2.3
