service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-orchestration-dispatcher-service:1.2.0.84.1
helmVersion: 0.2.58
