service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-issue-management-plane-service:1.0.0.22.1
helmVersion: 0.2.49
