service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-job-management-service:1.13.2.177.1
  hpa:
    minreplicas: 1
    maxreplicas: 1
helmVersion: 0.2.71
