service:
  probe:
    enabled: false
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-auth-management-plane-service:1.2.0.19.1
helmVersion: 0.2.36
