service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-orchestration-management-api-server-service:1.12.0.119.1
helmVersion: 0.2.58
