service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  containers:
    env:
    - name: filevault.basepath
      value: kv/data/qa/intcloud/ccgf/common/aws-intcloud-shrd-eks-qa-usw2
    - name: database.vaultPath
      value: rds/mysql
    - name: vault.url
      value: https://ha-vault.eks.iicsqa.uswest2.cloudtrust.rocks
    - name: filevault.landscape
      value: ccgf-qastaging-hawk-mgmt
  hpa:
    custommetric:
      cpu:
        average: 320m
      enabled: true
      memory:
        average: 2.4Gi
    maxreplicas: 5
    minreplicas: 2
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-configuration-manager-service:3.18.0.350.1
  pvc:
    resources:
      requests:
        storage: 1G
  serviceaccount: ccgf-cms
helmVersion: 0.2.77
