service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-connection-management-service:1.1.0.61.1
helmVersion: 0.2.51
