service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-job-management-plane-service:1.2.0.16.1
helmVersion: 0.2.52
