service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-data-source-management-service:1.13.0.124.1
helmVersion: 0.2.49
