service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  containers:
    env:
    - name: es_nodes
      value: vpc-ccgf-qastaging-hawk-es-6qjdyfhrquylf6aozxnbegu6bm.us-west-2.es.amazonaws.com
    - name: es_port
      value: '80'
    - name: CMS_BASE_URL
      value: configuration-manager
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-search-service:1.8.0.355.1
  resources:
    requests:
      cpu: 10.0m
      memory: 594Mi
  volumes:
    mounts:
    - name: efs-log
      mountPath: /var/log/infa/app/
      claimName: ccgf-hawk-log-pvc-func
helmVersion: 0.2.70
