service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-ingestion-jobhandler-service:1.1.0.25.1
helmVersion: 0.2.31
