service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-cloud-deployment-validator-service:1.6.0.299.1
helmVersion: 0.2.43
