service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-logger-service:1.1.0.184.1
  resources:
    requests:
      cpu: 10.0m
      memory: 424Mi
helmVersion: 0.2.72
