service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-oi-notification-digest-management-plane-service:1.0.0.19.1
helmVersion: 0.2.17
