service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-discovery-management-plane-service:1.2.0.24.1
helmVersion: 0.2.51
