service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-catalog-management-plane-service:1.0.0.17.1
helmVersion: 0.2.11
